version: '3'

services:
  postgresos:
    image: postgres
    restart: always
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'sourabh' 
      POSTGRES_PASSWORD: 'redhat'
      POSTGRES_DB: 'mypostgres'
 

  nextcloudos:
    image: nextcloud
    restart: always
    ports:
      - 8085:80
    volumes:
      - nextcloud_storage:/var/www/html
    environment:
      POSTGRES_HOST: 'postgresos'
      NEXTCLOUD_ADMIN_USER: 'sourabh' 
      NEXTCLOUD_ADMIN_PASSWORD: 'redhat'
    depends_on:
      - postgresos

volumes:
  postgres_storage:
  nextcloud_storage:
